name: 🔨 Build Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build .
        working-directory: .

      - name: Test
        run: go test ./...
        working-directory: .

      - name: install nuclei and nuclei templates
        run: go run -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
        
      - name: Race Condition Tests
        run: go run -race .
        working-directory: .
